name: Valitation
on: [push, workflow_dispatch, pull_request]
jobs:
  Validate:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Extract last user name from subscriptions.yaml
        id: extract-last-user
        uses: tj-actions/yaml@v2.1.0
        with:
          path: subscription.yaml
          text: |
            {{
              users := .users | map(.name);
              last_user := users[-1];
              {
                "last-user": last_user
              }
            }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Last User
        run: |
          last_user="${{ steps.extract-last-user.outputs.last-user }}"
          echo "The last user is ${last_user}"
