name: Valitation
on: [push, workflow_dispatch, pull_request]
jobs:
  Validate:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: echo
        run: echo "done"
      - name: Extract last user name from subscriptions.yaml
        id: extract-last-user
        uses: colpal/setup-yq@v1
        with:
          path: subscription.yaml
      - run: |
          last_user=$(echo "${{ steps.extract-last-user.outputs.contents }}" | jq '.users | map(.name) | .[-1]')
          echo "::set-output name=last-user::$last_user"
